apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs
  namespace: elastic-ha
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
