apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ha-es
  namespace: elastic-ha
spec:
  version: 7.16.1
  updateStrategy:
    changeBudget:
      maxSurge: -1
      maxUnavailable: 1
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data"]
      xpack.ml.enabled: false
    count: 3
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          # env:
          # - name: ES_JAVA_OPTS
          #   value: -Xms4g -Xmx4g
          resources:
            requests:
              memory: 12Gi
              cpu: 1
            limits:
              memory: 12Gi
              cpu: 4
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: aws-ebs
  http:
    service:
      spec:
        type: LoadBalancer
